branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
env:
  global:
    - secure: "eiQErNmzj3QcgXtfSslJWyR+Ncy9oOMRO50MBm4bn/WOLjBGo6cJq/SIb6fAmJASo4FhDkq8VjE36zNnz8TGdjuqIXAm5coI1RkOsOW/B3AS3aeKcWo7q5DPbcSpzmes7YyOqJI+YXmM6k8nhflZgucGL9QceiRdpXHWyM7FCQEpHYTYYwzlHPAykf2TQ1oYQrKXwmAO5d5UgRPCo1aXOuNdO1mHK2oc2Cmyt/U21v/5VjKRgjcEAzHFttNfliYOOoOCSLvDxQrdmUT82x/GVWYh/fstkpYVHXUr0mUsKfWVv7aXi9AOZTCLP7/n1hq2iDOknAn6iQFKIIYbBECXiDnxiaXAFymBFsJvCzqsnznoutfI2kVl4lTWjeU6jmkzLlY18tOj2V3snZ5bycsqsnx1c39kVs7XMGCEOj0RE1fkAHbgJX9YGwzx/z87E8KSs4sxjATaJhwx/Ns+EliJqF4vFo/On5ty//6CBy9rzb6lZa2wkWid9c91NS+c1dTzieKImpwvSJzCt50zXQb8deqaSqIeiYTje9CjvYiKtiiPk6KCLroIkogNO69gLm4t3mlfciqHinroP1pOthDSq7KigY/yZhb2va97lhf8Sa3RHIBw1RS0bxvhKJxgfBais+tbX6LOIE+jkB/Vg7pu532i0fkflfdsdGsUqLkR/gQ="
