branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
env:
  global:
    # travis encrypt -r gbic-ucsd/gbic-ucsd.github.io-source GIT_NAME="Olga Botvinnik" GIT_EMAIL=olga.botvinnik@gmail.com GH_TOKEN=<secret personal access token from github.com>
    - secure: "YDPqeERBwAFlFAaYf5LBaG6CZDPxSRsgP5HCAHv5kkAAtVdfp14Ly7EZV+8bSyUOaagE1kzcD1vUsJLAH7IIpPkoBA3IOgUd9UmqyDsfMk8iqqGXBKuB5/bf8b8zkKhM9ZQ0Rf054Hw4speg69Vrth+7jbR+9wjW9DV3UyzpG0w7tfjLlDgDkoUneYQDjMju7PykhKoOQxxVL6x8LFpkPrSZIOgs6F50XuTU9A7c97tQ1+YYQcK1LpeTHxQXtPvvGMhuG5xod/v5mHHUawtnDygHD0gVZ2QkA9pA0dV7+9LTDOWPS4zat3YIbsYoX1D5D0cvCpAHLy2z3TLnXdo/7zW9IW9FI69ZRnOvXkq/O8o0WHt28OeErWYOIwPV+Jgxcmd350Gf7Bo8O/yzKMZew8uqOx6QtX89FIrYbt3D7AwL92P/su22yo0sXh+/6TGHvcPxdVaQ92i62Y7EedCPDO1OyuQNvSqFeuuLQM2Au9ZVyUziivxR6TA1NVYuGlnBlBMApnPoO2xGc+Af5Bd8KKKXQg3twBQ4IaAbDUX7M6e3V1MZAOIf7wM/8/xYfFV69KEEGq6o3k7PXGP9oB6lsOeKCRZ8JDbM222hXVOLe9bhp3NxlG1AQzdsz1P93287ve9xYqnSnto/vXikh2gnt88/zpsQnKFGofbmvcsBtkk="
