branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- make html
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
env:
  global:
    secure: e0O6hYtA32avXcXy+/F9Lw0xGBlQGrKImGVl1SpQ6s6NEnGOWcY/jrpIbCjUVGXoSNpZ74TY/UXwyVJyOhHSD+7CIvysKGdXjZ0/7g94QgwjtAkxjoQGOZKvcKUg0vld/YJL/BsSa4lAUUnWdijj0vr3Vk8ADw1R+AuPjO0dNd9jFzrA7mKnF6PwMobTjYmizxmF5M/N48IIXMqwaTzB+h5+YTCJf9BytSKHsvP1LCFDTKKkKdKo3fQ9JzfcAwDQ1vfMBOoJabrudV3M9pMwyuuEAn7gPe6P72KynFwDCsSplzeNl3X2aKO3Fhp4mSo2a1wTXz5DrBMxAwPf3OvHBwZlctJbOmmSJSXbxbBVClLZH00asZi/0XEfq4pdpdHoW5On3xyOSf/c31jV3xcQTkuV8BHTXlVdyfCDQacn7K9osUH282lJEQEZ4oKLPCrYIfHeZEACu+LoEexcKd3zARhsgR5BmmELwbPgrSaAfGveztyj0VwL+6XoUJjzI74PJIKLT15rbHBH4ZksZ5/H3uCnrzwl3zdiTywzoA2CSNMc43AiECY2sTaEC6TTAEllEeuWXv0JmkD++PQgCoNnA5ADB3rwFEWh0f3hgJIYiKduJETTMqTSfwReS7fNIZQA67q2YDdrxg2TMW5DCvmXnrCDvVbXcp5zbVYpwiLep9c=
